export interface Keluarga {
  IdpegawaiKeluarga: number;
  IdrefValiditas: number;
  IdrefStatusData: number | null;
  CreatedDate: string;
  CreatedBy: number;
  Lampiran: string | null;
  AktaCerai: string | null;
  TanggalCerai: string | null;
  AktaNikah: string | null;
  TanggalMenikah: string | null;
  TempatLahir: string;
  TanggalLahir: string;
  Nama: string;
  IdrefStatusMenikah: number;
  StatusMenikah: string;
  IdrefHubungan: number;
  Hubungan: string;
  JenisKelamin: string;
  StatusTanggungan: string;
  Idpegawai: number;
  Idlama: number | null;
  IdrefStatusHidupKeluarga: string;
  IdrefPekerjaan: number;
  Pekerjaan: string;
  Esl1: string;
  UraianStatusValiditas: string;
}

export interface Profile {
  Idpegawai: number;
  Nip9: string;
  Nip18: string;
  Nik: string;
  Nama: string;
  KodeGolongan: string;
  KodeGolonganRuang: string;
  Jabatan: string;
  JenisJabatan: string;
  StatusPegawai: string;
  GelarDepan: string;
  GelarBelakang: string;
  Esl1: string;
  Esl2: string;
  Esl3: string;
  Esl4: string;
  Esl5: string;
  KdSatker: string;
  NamaSatker: string;
  TempatLahir: string;
  TanggalLahir: string;
  JenisKelamin: string;
  Agama: string;
  GolonganDarah: string;
  NoKartuPegawai: string;
  Npwp: string;
  AlamatKtp: string;
  KotaKtp: string;
  ProvinsiKtp: string;
  KodePosKtp: string;
  AlamatDomisili: string;
  KotaDomisili: string;
  ProvinsiDomisili: string;
  KodePosDomisili: string;
  NomorTelepon: string;
  Email: string;
  NoHp: string;
  NoKk: string;
  NamaKontakDarurat: string;
  NomorKontakDarurat: string;
  KodeOrganisasi: string;
  KodeIndukOrganisasi: string;
  Organisasi: string;
  Grading: number;
  IDRefJenisTugasBelajar: string;
  JenisTugasBelajar: string;
  IsPerpanjanganTB: boolean;
  TMTStatusPegawai: string;
  TanggalSKStatusPegawai: string;
}

export interface Profile2 {
  idPegawai: number;
  nip18: string;
  nip9: string;
  nama: string;
  gelarDepan: string;
  gelarBelakang: string;
  tempatLahir: string;
  tanggalLahir: string;
  idrefJenisKelamin: string;
  jenisKelamin: string;
  idrefAgama: number;
  agama: string;
  golonganDarah: string;
  noKartuPegawai: string;
  npwp: string;
  provinsiKTP: string;
  provinsiDomisili: string;
  nomorTelepon: string;
  email: string;
  noHp: string;
  noKk: string;
  namaKontakDarurat: string;
  nomorKontakDarurat: string;
  kdSatker: string;
  namaSatker: string;
  nik: string;
  jabatan: {
    idPegawaiJabatan: number;
    idJabatan: number;
    idJabatanAtasan: number;
    idRefNamaJabatan: number;
    namaJabatan: string;
    statusJabatan: string;
    esl1: string;
    esl2: string;
    esl3: string;
    esl4: string;
    idOrganisasi: number;
    kodeOrganisasi: string;
    kodeIndukOrganisasi: string;
    organisasi: string;
    tanggalMulai: string;
    grading: number;
    jenisJabatan: string;
    kodeEselon: string;
    uraianEselon: string;
    idRefJenjangJabatan: number;
    noSK: string;
    lampiran: string;
  }[];
  pangkat: {
    idPegawaiPangkat: number;
    idRefPangkat: number;
    namaPangkat: string;
    kodeGolongan: string;
    noSK: string;
    tanggalMulai: string;
    lampiran: string;
  };
  status: {
    idPegawaiStatus: number;
    idRefStatus: number;
    uraian: string;
    tanggalMulai: string;
    noSK: string;
  };
  grading: {
    idPegawaiGrading: number;
    grading: number;
    noSK: string;
    tanggalMulai: string;
  };
  statusPernikahan: string;
  id: {
    timestamp: number;
    machine: number;
    pid: number;
    increment: number;
    creationTime: string;
  };
  createdAt: string;
}
